### ISSUE TITLE
The 'Transpose characters around the cursor' command does nothing differing from the 'Transpose letters'

### ISSUE THREAD

**Issue by Apawn1979** [v4run/transpose#4]
As the title.

**Comment by v4run** [comment]
@Apawn1979 
**Transpose characters around the cursor** and **Transpose letters** are both default commands.
<img src="https://i.imgur.com/qeE5hFn.png" title="source: imgur.com" />

**Comment by Apawn1979** [comment]
And they do exactly the same thing?

**Comment by v4run** [comment]
From what I know, both the commands behave the same except when the cursor is at the end or beginning of a line. 'Transpose letters' swaps **line break**s while 'Transpose characters around the cursor' doesn't.

**Comment by v4run** [comment]
Closing the issue as the mentioned features are not part of the plugin.
